#pragma config(Sensor, S1,     colorS,         sensorEV3_Color)
#pragma config(Sensor, S2,     ultraS,         sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          Rmotor,        tmotorEV3_Large, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motorB,          Lmotor,        tmotorEV3_Large, PIDControl, reversed, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{


	float distance = SensorValue(ultraS);

	while(1){
		int LightValue = SensorValue(colorS);
		displayCenteredTextLine(6, "%d", LightValue);

		while(SensorValue(colorS) > 20){ // Right
		displayCenteredTextLine(6, "%d", LightValue);
		LightValue = SensorValue(colorS);
			setMotorSpeed(Rmotor, 30 );
			setMotorSpeed(Lmotor, 5 );}

		while(SensorValue(colorS) <= 20){ // LEFT
		displayCenteredTextLine(6, "%d", LightValue);
		LightValue = SensorValue(colorS);
			setMotorSpeed(Rmotor, 10 );
			setMotorSpeed(Lmotor, 40 );
		}
}}
